cluster:
  project: cms

apps:
  # ===== CMS DEV =====
  # cms-dev-grafana:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/grafana
  #   namespace: ci-dcmlp-openshift

  # cms-dev-influxdb:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/influxdb
  #   namespace: ci-dcmlp-openshift

  cms-dev-nginx:
    enabled: true
    repoURL: https://github.com/ahg3hc/helm-stacks.git
    targetRevision: main
    chartPath: cms-helm
    valuePath: cms-values/dev/nginx
    namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmachlq10:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmachlq10
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmeaslq05:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmeaslq05
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmeaslq05-old:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmeaslq05-old
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmeaslq05-mcm1all:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmeaslq05-mcm1all
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmeaslq05-mcm2miss:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmeaslq05-mcm2miss
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmpmeaslq05-mcm2rest:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmpmeaslq05-mcm2rest
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmptest1:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmptest1
  #   namespace: ci-dcmlp-openshift

  # cms-dev-telegraf-ppmptest2:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/telegraf-ppmptest2
  #   namespace: ci-dcmlp-openshift

  # cms-dev-cronjob-calc-axis:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/cronjob-calc-axis-test-avg
  #   namespace: ci-dcmlp-openshift

  # cms-dev-cronjob-calc-spindle:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/cronjob-calc-spindle-test-avg
  #   namespace: ci-dcmlp-openshift

  # cms-dev-cronjob-count-field:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/dev/cronjob-count-single-field
  #   namespace: ci-dcmlp-openshift

  # ===== CMS QA =====
  # cms-qa-grafana:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/grafana
  #   namespace: ci-dcmlp-openshift

  # cms-qa-influxdb:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/influxdb
  #   namespace: ci-dcmlp-openshift

  # cms-qa-influxdb3:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/influxdb3
  #   namespace: ci-dcmlp-openshift

  # cms-qa-nginx:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/nginx
  #   namespace: ci-dcmlp-openshift

  # cms-qa-telegraf-ppmpmachlq10:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/telegraf-ppmpmachlq10
  #   namespace: ci-dcmlp-openshift

  # cms-qa-telegraf-ppmpmachlq10-http:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/telegraf-ppmpmachlq10-http
  #   namespace: ci-dcmlp-openshift

  # cms-qa-telegraf-ppmpmeaslq05:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/telegraf-ppmpmeaslq05
  #   namespace: ci-dcmlp-openshift

  # cms-qa-telegraf-ppmpmeaslq05-http:
  #   enabled: true
  #   repoURL: https://github.com/ahg3hc/helm-stacks.git
  #   targetRevision: main
  #   chartPath: cms-helm
  #   valuePath: cms-values/qa/telegraf-ppmpmeaslq05-http
  #   namespace: ci-dcmlp-openshift
