deployment:
  enabled: true
  replicas: 0
  image:
    repository: image-registry.openshift-image-registry.svc:5000/ci-dcmlp-openshift-cms-dev/dcmlp-cm-telegraf
    tag: latest
  ports:
    - name: listener
      containerPort: 5687
  volumeMounts:
    - name: config-volume
      mountPath: /etc/telegraf/telegraf.conf
      subPath: telegraf.conf
      readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: dcmlp-cms-dev-telegraf-ppmptest1-config
  env:
    - name: INFLUXDB_TOKEN_WRITE
      valueFrom:
        secretKeyRef:
          name: dcmlp-cms-dev-influxdb-secret
          key: INFLUXDB_TOKEN_ALL_BUCKETS_WRITE
    - name: MQTT_USER
      valueFrom:
        secretKeyRef:
          name: dcmlp-solace-q-secret
          key: MQTT_USER
    - name: MQTT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dcmlp-solace-q-secret
          key: MQTT_PASSWORD
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 200Mi

service:
  enabled: false

route:
  enabled: false

configmap:
  enabled: true
  name: dcmlp-cms-dev-telegraf-ppmptest1-config
  data:
    telegraf.conf: |
      [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "5s"
          flush_jitter = "0s"
          precision = "1s"
          hostname = ""
          omit_hostname = false
          skip_processors_after_aggregators = false
          debug=true

      [[inputs.mqtt_consumer]]
          servers = ["mqtts://si0vm02988.de.bosch.com:10320"]
          topics = [
            "PPMP/Measurement/V3/EcP/lq05/#",
            "PPMP/Measurement/V3/HorP/lq05/#",
            "PPMP/Measurement/V3/BuP2/lq05/#",
            "PPMP/Measurement/V3/PkP/lq05/#",
            "PPMP/Measurement/V3/QueP1/lq05/#",
            "PPMP/Measurement/V3/FniP/lq05/#",
            "PPMP/Measurement/V3/HoP2/lq05/#",
            ]
          username = "${MQTT_USER}"
          password = "${MQTT_PASSWORD}"
          tls_ca = "/etc/telegraf/certs/Bosch-MQTT.pem"
          insecure_skip_verify = true
          data_format = "value"
          data_type = "string"
          [inputs.mqtt_consumer.tagpass]
            topic = [
              "PPMP/Measurement/V3/EcP/lq05/405497281000000000171240",
              "PPMP/Measurement/V3/BuP2/lq05/405497281000000000188572",
              "PPMP/Measurement/V3/PkP/lq05/405497281000000000216031",
              "PPMP/Measurement/V3/HorP/lq05/405497281000000000229422",
              "PPMP/Measurement/V3/HorP/lq05/405497281000000000177134",
              "PPMP/Measurement/V3/HorP/lq05/405497281000000000210237",
              "PPMP/Measurement/V3/HorP/lq05/405497281000000000284187",
              "PPMP/Measurement/V3/HorP/lq05/405497281000000000315446"
              ]

      [[processors.starlark]]
          script = "/etc/telegraf/star/PPMPMeasurementV3_lq05_mqtt_v3.0d.star"

      [[outputs.influxdb_v2]]
          urls = ["http://cms-dev-influxdb:8086"]
          token = "${INFLUXDB_TOKEN_WRITE}"
          organization = "DC"
          bucket = "DCMLP_CMS_DB_Test_Alerting"
          timeout = "30s"
          insecure_skip_verify = true
