deployment:
  enabled: true
  replicas: 0
  image:
    repository: image-registry.openshift-image-registry.svc:5000/ci-dcmlp-openshift-cms-dev/dcmlp-cm-telegraf
    tag: latest
  ports:
    - name: listener
      containerPort: 8080
  volumeMounts:
    - name: config-volume
      mountPath: /etc/telegraf/telegraf.conf
      subPath: telegraf.conf
      readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: dcmlp-cms-dev-telegraf-ppmpmachlq10-config
  env:
    - name: INFLUXDB_TOKEN_WRITE
      valueFrom:
        secretKeyRef:
          name: dcmlp-cms-dev-influxdb-secret
          key: INFLUXDB_TOKEN_ALL_BUCKETS_WRITE
    - name: MQTT_USER
      valueFrom:
        secretKeyRef:
          name: dcmlp-solace-q-secret
          key: MQTT_USER
    - name: MQTT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dcmlp-solace-q-secret
          key: MQTT_PASSWORD
  resources:
    limits:
      cpu: 20m
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 50Mi

service:
  enabled: false

route:
  enabled: false

configmap:
  enabled: true
  name: dcmlp-cms-dev-telegraf-ppmpmachlq10-config
  data:
    telegraf.conf: |
      [agent]
          interval = "10s"
          round_interval = true
          metric_batch_size = 1000
          metric_buffer_limit = 10000
          collection_jitter = "0s"
          flush_interval = "10s"
          flush_jitter = "0s"
          precision = ""
          hostname = ""
          omit_hostname = false
          skip_processors_after_aggregators = false
          debug=true

      [[inputs.mqtt_consumer]]
          servers = ["mqtts://si0vm02988.de.bosch.com:10320"]
          topics = [
            "PPMP/Machine/V3/EcP/lq10/#",
            "PPMP/Machine/V3/HorP/lq10/#",
            "PPMP/Machine/V3/BuP2/lq10/#",
            "PPMP/Machine/V3/PkP/lq10/#",
            "PPMP/Machine/V3/QueP1/lq10/#",
            "PPMP/Machine/V3/FniP/lq10/#",
            ]
          username = "${MQTT_USER}"
          password = "${MQTT_PASSWORD}"
          tls_ca = "/etc/telegraf/certs/Bosch-MQTT.pem"
          insecure_skip_verify = true
          data_format = "value"
          data_type = "string"
          [inputs.mqtt_consumer.tagpass]
            topic = [
              "PPMP/Machine/V3/HorP/lq10/405497281000000000177134",
              "PPMP/Machine/V3/HorP/lq10/405497281000000000284187",
              ]

      [[processors.starlark]]
          script = "/etc/telegraf/star/PPMPMachineV3_lq10_mqtt_v2.1.star"

      [[outputs.influxdb_v2]]
          urls = ["http://cms-dev-influxdb:8086"]
          token = "${INFLUXDB_TOKEN_WRITE}"
          organization = "DC"
          bucket = "DCMLP_CMS_DB_Test"
          timeout = "30s"
          insecure_skip_verify = true
