deployment:
  enabled: true
  replicas: 0
  image:
    repository: image-registry.openshift-image-registry.svc:5000/ci-dcmlp-openshift-cms-dev/dcmlp-cm-telegraf
    tag: latest
  ports:
    - name: listener
      containerPort: 8080
  volumeMounts:
    - name: config-volume
      mountPath: /etc/telegraf/telegraf.conf
      subPath: telegraf.conf
      readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: dcmlp-cms-qa-telegraf-ppmpmeaslq05-config
  env:
    - name: INFLUX_TOKEN
      valueFrom:
        secretKeyRef:
          name: dcmlp-cms-qa-influxdb-secret
          key: INFLUXDB_TOKEN_ALL_BUCKETS_WRITE
  resources:
    limits:
      cpu: 50m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 100Mi

service:
  enabled: false

route:
  enabled: false

configmap:
  enabled: true
  name: dcmlp-cms-qa-telegraf-ppmpmeaslq05-config
  data:
    telegraf.conf: |
      [agent]
        interval = "10s"
      [[outputs.influxdb_v2]]
        urls = ["http://dcmlp-cms-qa-influxdb:8086"]
        token = "$INFLUX_TOKEN"
        organization = "dcmlp"
        bucket = "ppmpmeaslq05"
      [[inputs.opcua]]
        endpoint = "opc.tcp://ppmpmeaslq05:4840"
