{{- if .Values.route }}
{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.route.toName | default .Release.Name }}
    weight: 100
  port:
    targetPort: {{ .Values.route.targetPort }}
  {{- if .Values.route.tls }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
    {{- if .Values.route.tls.certificate }}
    certificate: |
{{ .Values.route.tls.certificate | trim | indent 6 }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: |
{{ .Values.route.tls.key | trim | indent 6 }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: |
{{ .Values.route.tls.caCertificate | trim | indent 6 }}
    {{- end }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | default "None" }}
{{- end }}
{{- end }}
